logging:
  level:
    com.example.websocket: debug

spring:
  application:
    name: websocket
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 2MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/websocketDB
    username: root
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
      generate-ddl: true # Hibernate? DDL? ???? ??
      properties:
        hibernate:
          format_sql: true # SQL ??? ????? ??
          default_batch_fetch_size: 50 # ?? ?? ?? ?? ??
          show_sql: true
      open-in-view: false # Open Session in View ?? ???? (??? ? ????? ??? ??, ?? ? ??? ??)

file:
  upload:
    path:
      profileImg: /Users/seonoo/workspace/websocket/src/main/resources/static/profileImg/